package com.bnsf.model.ioc

import org.apache.spark.sql.types.StructType
import org.apache.spark.sql.types._
import org.apache.spark.sql.types.DecimalType

object Constants extends Serializable {

  val BODY: String = "body";
  val DECTECTOR: String = "detector";
  val DEC_TYPE_CODE: String = "detectorTypeCode";
  val DEC_TYPE_CODE_WILD: String = "WILD";
  val WHL_KIPS_DYN: String = "whl_kips_dyn";
  val EMPTY_STR: String = "";
  val NOT_APPLICABLE: String = "NA";
  val DATE_FORMAT_YYYY_MM_DD_T_HH_MM_SSZ: String = "yyyy-MM-dd'T'HH:mm:ss'Z'";

  val msgDtlSchema = StructType(Array(StructField("da_msg_id", LongType, true), StructField("da_meas_ts", TimestampType, true), StructField("da_msg_rcv_ts", TimestampType, true), StructField("da_detr_id", IntegerType, true), StructField("cret_id", StringType, true), StructField("cret_ts", TimestampType, true), StructField("lst_maint_id", StringType, true), StructField("lst_maint_ts", TimestampType, true), StructField("edr_detr_grp_id", LongType, true), StructField("aei_enbld_src_ind", StringType, true), StructField("da_aei_msg_prcsg_cd", StringType, true), StructField("vndr_cnst_msg_cnfdc_cd", StringType, true), StructField("cnst_msg_prcsg_ord_cd", StringType, true), StructField("cret_yr", IntegerType, true), StructField("cret_mo", IntegerType, true)))

  val detMeasSchema = StructType(Array(StructField("da_detr_meas_id", LongType, true), StructField("da_msg_id", LongType, true), StructField("da_detr_id", IntegerType, true), StructField("da_meas_typ_cd", StringType, true), StructField("da_detr_meas_stat_cd", StringType, true), StructField("da_detr_meas_val", DoubleType, true), StructField("da_detr_meas_val_txt", StringType, true), StructField("da_detr_meas_uom_cd", StringType, true), StructField("da_detr_meas_qual_cd", StringType, true), StructField("da_detr_meas_cfd_lvl", DoubleType, true), StructField("cret_id", StringType, true), StructField("cret_ts", TimestampType, true), StructField("lst_maint_id", StringType, true), StructField("lst_maint_ts", TimestampType, true), StructField("da_detr_meas_ts", TimestampType, true), StructField("cret_yr", IntegerType, true), StructField("cret_mo", IntegerType, true)))

  val trnMeasSchema = StructType(Array(StructField("da_trn_meas_id", LongType, true), StructField("da_msg_id", LongType, true), StructField("da_meas_typ_cd", StringType, true), StructField("da_trn_meas_val", DoubleType, true), StructField("da_trn_meas_val_txt", StringType, true), StructField("da_trn_meas_uom_cd", StringType, true), StructField("da_trn_meas_qual_cd", StringType, true), StructField("da_trn_meas_cfd_lvl", DoubleType, true), StructField("da_detr_calbr_cfd_lvl", DoubleType, true), StructField("trn_sid_cd", StringType, true), StructField("da_trn_meas_stat_cd", StringType, true), StructField("cret_id", StringType, true), StructField("cret_ts", TimestampType, true), StructField("lst_maint_id", StringType, true), StructField("lst_maint_ts", TimestampType, true), StructField("da_trn_meas_ts", TimestampType, true), StructField("cret_yr", IntegerType, true), StructField("cret_mo", IntegerType, true)))

  val eqpMeasSchema = StructType(Array(StructField("da_eqp_meas_id", LongType, true), StructField("da_msg_id", LongType, true), StructField("da_eqp_seq_nbr", ShortType, true), StructField("da_meas_typ_cd", StringType, true), StructField("da_eqp_meas_stat_cd", StringType, true), StructField("da_eqp_meas_val", DoubleType, true), StructField("da_eqp_meas_val_txt", StringType, true), StructField("da_eqp_meas_uom_cd", StringType, true), StructField("da_eqp_meas_qual_cd", StringType, true), StructField("da_eqp_meas_cfd_lvl", DoubleType, true), StructField("da_detr_calbr_cfd_lvl", DoubleType, true), StructField("trn_sid_cd", StringType, true), StructField("cret_id", StringType, true), StructField("cret_ts", TimestampType, true), StructField("pscl_clstr_mbr_nbr", IntegerType, true), StructField("lst_maint_id", StringType, true), StructField("lst_maint_ts", TimestampType, true), StructField("da_eqp_meas_ts", TimestampType, true), StructField("cret_yr", IntegerType, true), StructField("cret_mo", IntegerType, true)))

  val eqpCmpMeasSchema = StructType(Array(StructField("da_eqcmpnt_meas_id", LongType, true), StructField("da_msg_id", LongType, true), StructField("da_eqp_seq_nbr", ShortType, true), StructField("da_eqp_cmpnt_typ_cd", StringType, true), StructField("aar_eqp_cmpnt_loc_cd", StringType, true), StructField("da_meas_typ_cd", StringType, true), StructField("da_eqp_cmpnt_meas_val", DoubleType, true), StructField("da_eqp_cmpnt_meas_val_txt", StringType, true), StructField("da_eqp_cmpnt_meas_uom_cd", StringType, true), StructField("da_eqp_cmpnt_meas_qual_cd", StringType, true), StructField("da_eqp_cmpnt_meas_cfd_lvl", DoubleType, true), StructField("da_eqp_cmpnt_meas_stat_cd", StringType, true), StructField("da_detr_calbr_cfd_lvl", DoubleType, true), StructField("trn_sid_cd", StringType, true), StructField("trn_axl_pos", ShortType, true), StructField("eqp_trn_cst_pos", ShortType, true), StructField("aar_eqp_trck_loc_cd", StringType, true), StructField("aar_eqp_axl_loc_cd", StringType, true), StructField("aar_eqp_cmpnt_eqp_sid_cd", StringType, true), StructField("cret_id", StringType, true), StructField("cret_ts", TimestampType, true), StructField("pscl_clstr_mbr_nbr", IntegerType, true), StructField("lst_maint_id", StringType, true), StructField("lst_maint_ts", TimestampType, true), StructField("trn_trck_pos", ShortType, true), StructField("da_eqp_cmpnt_meas_ts", TimestampType, true), StructField("cret_yr", IntegerType, true), StructField("cret_mo", IntegerType, true)))

  val eqpCstSchema = StructType(Array(StructField("da_msg_id", LongType, true), StructField("da_eqp_seq_nbr", ShortType, true), StructField("eqp_strt_trn_axl_pos", ShortType, true), StructField("eqp_end_trn_axl_pos", ShortType, true), StructField("eqp_init", StringType, true), StructField("eqp_numb", StringType, true), StructField("da_eqp_typ_cd", StringType, true), StructField("da_aar_eqp_cfg_typ_cd", StringType, true), StructField("trn_eqp_pos", ShortType, true), StructField("aar_trn_eqp_orntn_cd", StringType, true), StructField("da_eqp_mat_ts", TimestampType, true), StructField("da_eqp_mat_cfd_lvl", DoubleType, true), StructField("cret_id", StringType, true), StructField("cret_ts", TimestampType, true), StructField("lst_maint_id", StringType, true), StructField("lst_maint_ts", TimestampType, true), StructField("da_eqp_ld_mty_cd", StringType, true), StructField("aar_eqp_typ_cd", StringType, true), StructField("stcc", StringType, true), StructField("cmdty_abbr", StringType, true), StructField("drf_gear_typ", StringType, true), StructField("bld_dt", DateType, true), StructField("grs_rail_wgt", IntegerType, true), StructField("da_haz_matl_eqp_ind", StringType, true), StructField("car_kind", StringType, true), StructField("cret_yr", IntegerType, true), StructField("cret_mo", IntegerType, true)))

  val trnMatSchema = StructType(Array(StructField("da_msg_id", LongType, true), StructField("trn_id", StringType, true), StructField("trn_sch_dpt_dt", DateType, true), StructField("da_trn_mat_ts", TimestampType, true), StructField("da_trn_mat_cfd_lvl", DoubleType, true), StructField("cret_id", StringType, true), StructField("cret_ts", TimestampType, true), StructField("lst_maint_id", StringType, true), StructField("lst_maint_ts", TimestampType, true), StructField("da_key_trn_ind", StringType, true), StructField("da_hhft_trn_ind", StringType, true), StructField("cret_yr", IntegerType, true), StructField("cret_mo", IntegerType, true)))

  val detrSttcSchema = StructType(Array(StructField("da_detr_sttc_id", LongType, true), StructField("da_sttc_typ_cd", StringType, true), StructField("da_detr_sttc_cmp_ts", TimestampType, true), StructField("da_detr_sttc_stat_cd", StringType, true), StructField("da_detr_id", IntegerType, true), StructField("da_detr_sttc_val", DoubleType, true), StructField("da_detr_sttc_val_txt", StringType, true), StructField("da_detr_sttc_uom_cd", StringType, true), StructField("da_detr_sttc_cfd_lvl", DoubleType, true), StructField("cret_id", StringType, true), StructField("cret_ts", TimestampType, true), StructField("lst_maint_id", StringType, true), StructField("lst_maint_ts", TimestampType, true), StructField("da_lst_msg_id", LongType, true), StructField("da_detr_sttc_qual_cd", StringType, true), StructField("cret_yr", IntegerType, true), StructField("cret_mo", IntegerType, true)))

  val trnSttcSchema = StructType(Array(StructField("da_trn_sttc_id", LongType, true), StructField("da_sttc_typ_cd", StringType, true), StructField("da_trn_sttc_cmp_ts", TimestampType, true), StructField("da_trn_sttc_stat_cd", StringType, true), StructField("trn_id", StringType, true), StructField("trn_sch_dpt_dt", DateType, true), StructField("da_trn_sttc_val", DoubleType, true), StructField("da_trn_sttc_val_txt", StringType, true), StructField("da_trn_sttc_uom_cd", StringType, true), StructField("da_trn_sttc_cfd_lvl", DoubleType, true), StructField("cret_id", StringType, true), StructField("cret_ts", TimestampType, true), StructField("lst_maint_id", StringType, true), StructField("lst_maint_ts", TimestampType, true), StructField("da_lst_msg_id", LongType, true), StructField("da_trn_sttc_qual_cd", StringType, true), StructField("cret_yr", IntegerType, true), StructField("cret_mo", IntegerType, true)))

  val eqpSttcSchema = StructType(Array(StructField("da_eqp_sttc_id", LongType, true), StructField("da_lst_msg_id", LongType, true), StructField("da_sttc_typ_cd", StringType, true), StructField("da_eqp_sttc_cmp_ts", TimestampType, true), StructField("da_eqp_sttc_stat_cd", StringType, true), StructField("eqp_init", StringType, true), StructField("eqp_numb", StringType, true), StructField("da_eqp_sttc_val", DoubleType, true), StructField("da_eqp_sttc_val_txt", StringType, true), StructField("da_eqp_sttc_uom_cd", StringType, true), StructField("da_eqp_sttc_cfd_lvl", DoubleType, true), StructField("cret_id", StringType, true), StructField("cret_ts", TimestampType, true), StructField("pscl_clstr_mbr_nbr", IntegerType, true), StructField("lst_maint_id", StringType, true), StructField("lst_maint_ts", TimestampType, true), StructField("da_eqp_sttc_qual_cd", StringType, true), StructField("cret_yr", IntegerType, true), StructField("cret_mo", IntegerType, true)))

  val eqpCmpSttcSchema = StructType(Array(StructField("da_eqcmpnt_sttc_id", LongType, true), StructField("da_sttc_typ_cd", StringType, true), StructField("da_eqp_cmpnt_sttc_cmp_ts", TimestampType, true), StructField("da_eqp_cmpnt_sttc_stat_cd", StringType, true), StructField("eqp_init", StringType, true), StructField("eqp_numb", StringType, true), StructField("da_eqp_cmpnt_typ_cd", StringType, true), StructField("aar_eqp_cmpnt_loc_cd", StringType, true), StructField("da_eqp_cmpnt_sttc_val", DoubleType, true), StructField("da_eqp_cmpnt_sttc_val_txt", StringType, true), StructField("da_eqp_cmpnt_sttc_uom_cd", StringType, true), StructField("da_eqp_cmpnt_sttc_cfd_lvl", DoubleType, true), StructField("aar_eqp_trck_loc_cd", StringType, true), StructField("aar_eqp_axl_loc_cd", StringType, true), StructField("aar_eqp_cmpnt_eqp_sid_cd", StringType, true), StructField("cret_id", StringType, true), StructField("cret_ts", TimestampType, true), StructField("pscl_clstr_mbr_nbr", IntegerType, true), StructField("lst_maint_id", StringType, true), StructField("lst_maint_ts", TimestampType, true), StructField("da_lst_msg_id", LongType, true), StructField("da_eqp_cmpnt_sttc_qual_cd	", StringType, true), StructField("cret_yr", IntegerType, true), StructField("cret_mo", IntegerType, true)))
}

